## Importacion de pandas

In [1]:
import pandas as pd

## Cargar desde un CSV

In [2]:
import pandas as pd
import csv

# Usamos parámetros extra para manejar el error de la fila 18303
try:
    df = pd.read_csv(
        '../data/raw/incidentes_viales.csv', 
        encoding='utf-8',        # Para tildes y eñes
        sep=None,                  # Detecta si es coma o punto y coma
        engine='python',           # Motor más flexible para errores
        quoting=csv.QUOTE_NONE,    # Ignora comillas problemáticas
        on_bad_lines='warn'        # Salta líneas corruptas y avisa
    )
    print("¡Carga exitosa! Dataset listo para el taller.")
    display(df.head())             # Punto 4 de tu evidencia
except Exception as e:
    print(f"No se pudo cargar: {e}")

C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 9692: Expected 19 fields in line 9692, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 9710: Expected 19 fields in line 9710, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 15065: Expected 19 fields in line 15065, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 15066: Expected 19 fields in line 15066, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 15469: Expected 19 fields in line 15469, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 15551: Expected 19 fields in line 15551, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 16044: Expected 19 fields in line 16044, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 16651: Expected 19 fields in line 16651, saw 20

  df = pd.read_csv(
C:\Users\felip\AppData\Local\Temp\ipykernel_23412\1029169083.py:6: ParserWarning: Skipping line 16737: Expected 19 fields in line 16737, saw 20

  df = pd.read_csv(

¡Carga exitosa! Dataset listo para el taller.

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
2015,1013,Caida Ocupante,CR 46 CL 43,CR 046 043 000 00000,Tramo de via,A000259731,21/10/2015 05:58:00,2015-10-21T10:58:00.000Z,Con heridos,10,1508668,10,Barrio Colón,La Candelaria,"""[-75.5688011014","6.24312304123]""",834949.69,1182357.34
2015,1020,Choque,CR 43 A CL 29,CR 043 A 029 000 00000,Tramo de via,A000261725,05/11/2015 03:00:00,2015-11-05T08:00:00.000Z,Solo daños,11,1510621,10,San Diego,La Candelaria,"""[-75.5693883283","6.22870030622]""",834880.17,1180762.02
2015,0205,Otro,CR 46 CL 37,CR 046 037 000 00000,Tramo de via,A000259739,21/10/2015 07:40:00,2015-10-21T12:40:00.000Z,Con heridos,10,1508691,02,La Francia,Santa Cruz,"""[-75.5503911403","6.29869502502]""",837004.94,1188499.17
2015,0101,Atropello,CR 34 CL 112,CR 034 112 000 00000,Tramo de via,A000259752,21/10/2015 12:00:00,2015-10-21T17:00:00.000Z,Con heridos,10,1508694,01,Santo Domingo Savio No. 1,Popular,"""[-75.5442195069","6.30019383306]""",837688.53,1188663.05
2015,1504,Choque,CR 50 CL 14,CR 050 014 000 00000,Tramo de via,A000259949,03/11/2015 06:16:00,2015-11-03T11:16:00.000Z,Solo daños,11,1510634,15,Santa Fé,Guayabal,"""[-75.578180998","6.21699243701]""",833903.11,1179469.60

### Inpeccion rapida

In [3]:
df.head() #Muestra las primeras 5 filas. Te da una idea de las columnas y los valores

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
2015,1013,Caida Ocupante,CR 46 CL 43,CR 046 043 000 00000,Tramo de via,A000259731,21/10/2015 05:58:00,2015-10-21T10:58:00.000Z,Con heridos,10,1508668,10,Barrio Colón,La Candelaria,"""[-75.5688011014","6.24312304123]""",834949.69,1182357.34
2015,1020,Choque,CR 43 A CL 29,CR 043 A 029 000 00000,Tramo de via,A000261725,05/11/2015 03:00:00,2015-11-05T08:00:00.000Z,Solo daños,11,1510621,10,San Diego,La Candelaria,"""[-75.5693883283","6.22870030622]""",834880.17,1180762.02
2015,0205,Otro,CR 46 CL 37,CR 046 037 000 00000,Tramo de via,A000259739,21/10/2015 07:40:00,2015-10-21T12:40:00.000Z,Con heridos,10,1508691,02,La Francia,Santa Cruz,"""[-75.5503911403","6.29869502502]""",837004.94,1188499.17
2015,0101,Atropello,CR 34 CL 112,CR 034 112 000 00000,Tramo de via,A000259752,21/10/2015 12:00:00,2015-10-21T17:00:00.000Z,Con heridos,10,1508694,01,Santo Domingo Savio No. 1,Popular,"""[-75.5442195069","6.30019383306]""",837688.53,1188663.05
2015,1504,Choque,CR 50 CL 14,CR 050 014 000 00000,Tramo de via,A000259949,03/11/2015 06:16:00,2015-11-03T11:16:00.000Z,Solo daños,11,1510634,15,Santa Fé,Guayabal,"""[-75.578180998","6.21699243701]""",833903.11,1179469.60

In [4]:
df.tail() ## Muestra las últimas 5 filas. Útil para ver si hay datos "basura" al final.

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
2018,1204,Choque,CL 43 CR 88,CL 043 088 000 00000,Interseccion,A000844586,03/08/2018 06:25:00,2018-08-03T11:25:00.000Z,Con heridos,8,1636998,12,La América,La América,"""[-75.6067693761","6.25041777924]""",830748.89,1183176.38
2018,NaN,Otro,CL 999 CR 999,CL 999 999 000 00000,Lote o Predio,A000844584,03/08/2018 06:50:00,2018-08-03T11:50:00.000Z,Con heridos,8,1636900,Sin Inf,NaN,NaN,"""[-75.7037762763","6.22141524356]""",820000.00,1180000.00
2018,1507,Atropello,CR 52 CL 5,CR 052 005 000 00000,Tramo de via,A000844594,03/08/2018 09:07:00,2018-08-03T14:07:00.000Z,Con heridos,8,1636905,15,Campo Amor,Guayabal,"""[-75.5838651883","6.21123660046]""",833272.02,1178834.65
2018,NaN,Choque,CR 63 CL 75 B,CR 063 075 B 000 00000,Tramo de via,A000845215,03/08/2018 10:00:00,2018-08-03T15:00:00.000Z,Solo daños,8,1637292,Sin Inf,NaN,NaN,"""[-75.7037762763","6.22141524356]""",820000.00,1180000.00
2018,1018,Choque,CL 58 CR 49,CL 058 049 000 00000,Tramo de via,A000844812,03/08/2018 10:25:00,2018-08-03T15:25:00.000Z,Solo daños,8,1636945,10,Villa Nueva,La Candelaria,"""[-75.563547107",6.2,NaN,NaN

In [5]:
df.shape # Muestra el número de filas y columnas. Te dice cuántos datos tienes para trabajar.

(18294, 18)

In [6]:
df.info() # Te dice el tipo de datos de cada columna y si hay valores nulos. Es clave para entender tu dataset.

<class 'pandas.core.frame.DataFrame'>
Index: 18294 entries, 2015 to 2018
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AÑO                    16923 non-null  object
 1   CBML                   18294 non-null  object
 2   CLASE_ACCIDENTE        18294 non-null  object
 3   DIRECCION              18266 non-null  object
 4   DIRECCION ENCASILLADA  18205 non-null  object
 5   DISEÑO                 18282 non-null  object
 6   EXPEDIENTE             18294 non-null  object
 7   FECHA_ACCIDENTE        18294 non-null  object
 8   FECHA_ACCIDENTES       18294 non-null  object
 9   GRAVEDAD_ACCIDENTE     18294 non-null  int64
 10  MES                    18294 non-null  object
 11  NRO_RADICADO           18294 non-null  object
 12  NUMCOMUNA              16922 non-null  object
 13  BARRIO                 17426 non-null  object
 14  COMUNA                 18294 non-null  object
 15  LOCATION               18294 non-null  object
 16  X                      18293 non-null  float64
 17  Y                      18293 non-null  float64
dtypes: float64(2), int64(1), object(15)
memory usage: 2.7+ MB

In [7]:
df.describe() # Te da estadísticas básicas de las columnas numéricas. Útil para detectar outliers o errores de captura.

       GRAVEDAD_ACCIDENTE              X             Y
count        18294.000000   18293.000000  1.829300e+04
mean             7.511206  832937.342905  1.182849e+06
std              2.907992    4173.947732  3.173420e+03
min              1.000000  820000.000000  1.172359e+06
25%              5.000000  832258.240000  1.180390e+06
50%              8.000000  834090.610000  1.182862e+06
75%             10.000000  835184.630000  1.185072e+06
max             12.000000  840616.130000  1.193391e+06

In [9]:
df.describe(include='object') # Para ver estadísticas de columnas categóricas, como conteos únicos y el valor más frecuente.

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION
count,16923,18294,18294,18266,18205,18282,18294,18294,18294,18294,18294,16922,17426,18294,18294
unique,333,8,8397,7940,12,18276,16650,16650,3,18294,26,305,24,6559,6560
top,1019,Choque,CR 999 CL 999,0,Tramo de via,A000591827,11/07/2016 19:30:00,2016-07-12T00:30:00.000Z,Con heridos,1508668,10,La Candelaria,La Candelaria,"""[-75.7037762763","6.22141524356]"""
freq,356,12229,168,538,12841,2,5,5,10130,1,3492,356,3496,1343,1343